### ISSUE TITLE
HA 2022.08 b0 -> not working anymore

### ISSUE THREAD

**Issue by coreGreenberet** [JoDehli/PyLoxone_beta#4]
All components are not displayin any data.
The HA logs are displaying this errors:

```
2022-07-28 11:43:24.505 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up loxone platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/loxone/sensor.py", line 61, in async_setup_entry
miniserver = get_miniserver_from_config_entry(hass, config_entry)
File "/config/custom_components/loxone/__init__.py", line 71, in get_miniserver_from_config_entry
return hass.data[DOMAIN][config_entry.entry_id]
KeyError: '92d7566fdcf75a10a6caea4559f078e4'
2022-07-28 11:43:24.507 ERROR (MainThread) [homeassistant.components.switch] Error while setting up loxone platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/loxone/switch.py", line 22, in async_setup_entry
miniserver = get_miniserver_from_config_entry(hass, config_entry)
File "/config/custom_components/loxone/__init__.py", line 71, in get_miniserver_from_config_entry
return hass.data[DOMAIN][config_entry.entry_id]
KeyError: '92d7566fdcf75a10a6caea4559f078e4'
2022-07-28 11:43:24.508 ERROR (MainThread) [homeassistant.components.cover] Error while setting up loxone platform for cover
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/loxone/cover.py", line 44, in async_setup_entry
miniserver = get_miniserver_from_config_entry(hass, config_entry)
File "/config/custom_components/loxone/__init__.py", line 71, in get_miniserver_from_config_entry
return hass.data[DOMAIN][config_entry.entry_id]
KeyError: '92d7566fdcf75a10a6caea4559f078e4'
2022-07-28 11:43:24.509 ERROR (MainThread) [homeassistant.components.light] Error while setting up loxone platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/loxone/light.py", line 33, in async_setup_entry
miniserver = get_miniserver_from_config_entry(hass, config_entry)
File "/config/custom_components/loxone/__init__.py", line 71, in get_miniserver_from_config_entry
return hass.data[DOMAIN][config_entry.entry_id]
KeyError: '92d7566fdcf75a10a6caea4559f078e4'
2022-07-28 11:43:24.511 ERROR (MainThread) [homeassistant.components.climate] Error while setting up loxone platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/loxone/climate.py", line 55, in async_setup_entry
miniserver = get_miniserver_from_config_entry(hass, config_entry)
File "/config/custom_components/loxone/__init__.py", line 71, in get_miniserver_from_config_entry
return hass.data[DOMAIN][config_entry.entry_id]
KeyError: '92d7566fdcf75a10a6caea4559f078e4'
2022-07-28 11:43:24.512 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up loxone platform for alarm_control_panel
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/loxone/alarm_control_panel.py", line 43, in async_setup_entry
miniserver = get_miniserver_from_config_entry(hass, config_entry)
File "/config/custom_components/loxone/__init__.py", line 71, in get_miniserver_from_config_entry
return hass.data[DOMAIN][config_entry.entry_id]
KeyError: '92d7566fdcf75a10a6caea4559f078e4'
```

**Comment by JoDehli** [comment]
@coreGreenberet try the newest version.

**Comment by JoDehli** [comment]
@coreGreenberet in version 0.0.3 binary sensors are added. Maybe major changes for automation will be required.

**Comment by coreGreenberet** [comment]
@JoDehli yes it's working again =)
Some sensors got readded with a new id i suppose as some were unavailable but at the same time there was a new sensor with the same name

**Comment by coreGreenberet** [comment]
At the moment I have to restart HA a few times until the integration is working again.
I'm getting these errors on startup.

Probably not all components are running already and HA is through the startup to busy for the pyloxone integration
```
2022-08-02 11:50:34.487 ERROR (MainThread) [custom_components.loxone.pyloxone_api.miniserver] An error "" occurred while requesting URL('https://<REMOVED__FOR_PRIVACY>.dyndns.loxonecloud.com/').
2022-08-02 11:50:34.528 ERROR (MainThread) [custom_components.loxone.pyloxone_api.miniserver] Error getting public key and config json. Please check host and port.
2022-08-02 11:50:34.529 ERROR (MainThread) [custom_components.loxone.pyloxone_api.miniserver] Try to get json reponse via browser by visiting the http://{ip-address-of-your-loxone}:{port}/data/LoxAPP3.json
```

**Comment by coreGreenberet** [comment]
Reboot is still required.
In the last case I've upgraded it to beta 6

**Comment by coreGreenberet** [comment]
Not sure If I should create another issue for this or if it is part of this one.
It looks like that the connectivity between HA and loxone is now really unstable. I can't tell if it is because of the HA beta (now updating to 2022.8.1 release) or this integration, but afte a while I'm not getting any updates from loxone and I can't send commands to loxone either.

**Comment by JoDehli** [comment]
@coreGreenberet do you use alarms in your installation. I found one issue that causes the connection to quit. But it happen only when sending a arm or disarm command with a empty code on alarm panels. 

All other things work well on my system.

**Comment by coreGreenberet** [comment]
I'm using alarms, but they are not controlled via HA

**Comment by JoDehli** [comment]
@coreGreenberet try the newest version. Make sure you delete the custom folder completely before copy over the new files. 

I can not do more as I not have any issue. Maybe try only local access.

**Comment by JoDehli** [comment]
@coreGreenberet can paste the result of the following command here: 

https://dns.loxonecloud.com/?getip&snr={REPLACE_WITH_YOUR_SERIAL}&json=true

{REPLACE_WITH_YOUR_SERIAL} => your serial without the curly brackets!

Of course do blank out all private information like your IP or your Serial number. 

What I want to look is your DataCenter entry.

**Comment by coreGreenberet** [comment]
{"cmd":"getip","Code":200,"IPHTTPS":"<IP-ADDRESS>:54549","PortOpenHTTPS":true,"RemoteConnect":true,"DNS-Status":"registered","DataCenter":"loxonecloud.com"}

The request took really long. probably 10? seconds. On the second try with enabled browser debugging tools it took 6 seconds.

**Comment by coreGreenberet** [comment]
> @coreGreenberet try the newest version. Make sure you delete the custom folder completely before copy over the new files.
> 
> I can not do more as I not have any issue. Maybe try only local access.

Normally I'm just doing an update via hacs. Now I did it with delete and reinstall on 0.0.5. 
I will keep you updated.

**Comment by coreGreenberet** [comment]
problem is still existing. after a while the connection will drop and I have to restart HA to get new data

**Comment by JoDehli** [comment]
@coreGreenberet have you the same problems with the normal pyloxone? I can try to find the problem next week. But it is difficult because I have no problems on my machine.

**Comment by coreGreenberet** [comment]
The normal pyloxone did stop working a time ago. That Was one of the reasons why I've switched to this one.
I will try to recreate the issue with more logging

**Comment by JoDehli** [comment]
@coreGreenberet most of the problems which I had in the past was because of the external connection. Best would be you connect via local connection. Then pyloxone should work perfectly fine. That is how I connect.

**Comment by JoDehli** [comment]
@coreGreenberet try this log configuration: 

```yaml
logger:
  default: critical
  logs:
    httpx: critical
    homeassistant: critical
    custom_components.loxone: debug
    custom_components.pyloxone_api: debug
    custom_components.loxone.pyloxone_api.wsclient: debug

```

**Comment by JoDehli** [comment]
@coreGreenberet I had a similar connection lost last night. I do not know why but maybe with the log I can find the problem. I try my best.

**Comment by JoDehli** [comment]
@coreGreenberet Please try the newest version. 

I think it is more stable but still not working perfect. I do not know what they changed on the aiohttp package but it seams the error handling is different. With the new beta version I have much more problems than with the old version.

**Comment by JoDehli** [comment]
@coreGreenberet try the newest 0.0.6.

**Comment by JoDehli** [comment]
@coreGreenberet It is not working and I do not exactly know why. I could be a Loxone bug in combination with the used aiohttp websocket library. Sorry at the moment I do not know to fix it.

**Comment by coreGreenberet** [comment]
I've just installed 0.7 and enabled the debug output. I will keep you updated

**Comment by JoDehli** [comment]
@coreGreenberet it is still not working.

**Comment by JoDehli** [comment]
@coreGreenberet the latest version worked for me over night. I can give it a try if you want.

**Comment by coreGreenberet** [comment]
It's running stable now for a few hours. Let us see what the night brings =)

**Comment by JoDehli** [comment]
@coreGreenberet for me it was stable the second night. Interesting is if it is stable when it makes a token refresh.

**Comment by coreGreenberet** [comment]
@jodehli night was fine. However I've initiated a reboot of the miniserver and the connection is lost again

**Comment by JoDehli** [comment]
@coreGreenberet that is not fixed yet I know. 
 But as long as you not reboot it should be stable.

**Comment by coreGreenberet** [comment]
@JoDehli looks stable so far
